version: '3'

services:
  where:
    container_name: where
    build: .
    tty: true
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - .:/home/node/app

  where_postgres:
    container_name: where_postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

networks:
  app-network:
    driver: bridge
