export { default as Dashboard } from './dashboard/dashboard'
export { default as Home } from './home/home'
export { default as Login, LoginGetServerSideProps } from './login/login'
export { default as NotFound } from './not-found/not-found'
export { default as Register } from './register/register'
